FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN yarn install

RUN yarn build

EXPOSE 8018

EXPOSE 9856

CMD [ "yarn","start" ]

# RUN rm -rf /node_modules

# RUN npm install

# RUN npm run dev